package main

import (
	"fmt"
	"syscall"
)

const (
	LINUX_REBOOT_MAGIC1  = syscall.LINUX_REBOOT_MAGIC1
	LINUX_REBOOT_MAGIC2  = syscall.LINUX_REBOOT_MAGIC2
	LINUX_REBOOT_MAGIC2A = 0x05121996
	LINUX_REBOOT_MAGIC2B = 0x16041998
	LINUX_REBOOT_MAGIC2C = 0x20112000
)

func main() {
	fmt.Printf("LINUX_REBOOT_MAGIC1  = 0x%08X (%d)\n", LINUX_REBOOT_MAGIC1, LINUX_REBOOT_MAGIC1)
	fmt.Printf("LINUX_REBOOT_MAGIC2  = 0x%08X (%d)\n", LINUX_REBOOT_MAGIC2, LINUX_REBOOT_MAGIC2)
	fmt.Printf("LINUX_REBOOT_MAGIC2A = 0x%08X (%d)\n", LINUX_REBOOT_MAGIC2A, LINUX_REBOOT_MAGIC2A)
	fmt.Printf("LINUX_REBOOT_MAGIC2B = 0x%08X (%d)\n", LINUX_REBOOT_MAGIC2B, LINUX_REBOOT_MAGIC2B)
	fmt.Printf("LINUX_REBOOT_MAGIC2C = 0x%08X (%d)\n", LINUX_REBOOT_MAGIC2C, LINUX_REBOOT_MAGIC2C)
}
